version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    command: bash -c "if [ ! -d ./src/data/migrations ]; then npm run migration:complete && npm run start; else npm run start; fi"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres-data:
